# Generated by Django 2.2 on 2019-04-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(default='null', editable=False, upload_to='thumbs/'),
            preserve_default=False,
        ),
    ]
